export const keywords = [
  'Pet Love',
  'pets adoption',
  'animal shelter',
  'veterinarians',
  'pet adoption community',
  'adopt pets',
  'pet adoption',
  'pet collaboration',
  'pet transit',
  'responsible pet adoption',
  'pet community',
  'animal welfare',
  'pets in need',
  'community collaboration',
  'animal lovers',
  'pet lovers',
  'pet adoption program',
  'animal adoption',
  'pets love',
  'pets community',
  'animal community',
  'home for pets',
  'positive pet adoption',
  'adopting pets',
  'pets adoption program',
  'pets adoption community',
  'animal transit',
  'pet transit program',
  'pet adoption initiative',
  'pet adoption campaign',
  'pets in shelters',
  'pet welfare',
  'pet loving community',
  'pets in loving homes',
  'pet adoption support',
  'pet adoption movement',
  'pet adoption mission',
  'animal adoption program',
  'pet loving',
  'animal loving community',
  'pet adoption charity',
  'pet adoption drive',
  'pet adoption movement',
  'pets loving homes',
  'pet adoption advocate',
  'pet adoption volunteer',
  'pet adoption fundraising',
  'pet adoption event',
  'pet adoption awareness',
  'pet adoption partnership',
  'pet adoption organization',
  'pet adoption initiative',
  'pet adoption cause',
  'pet adoption support group',
  'pet adoption outreach',
  'pet adoption assistance',
  'pet adoption campaign',
  'pet adoption assistance',
  'pet adoption sponsorship',
  'pet adoption assistance program',
  'pet adoption community outreach',
  'pet adoption community support',
  'pet adoption awareness campaign',
]
